name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            name: "UCI_RustyPigeon_win"
          - target: x86_64-unknown-linux-musl
            archive: zip
            name: "UCI_RustyPigeon_linux"
          - target: x86_64-apple-darwin
            archive: zip
            name: "UCI_RustyPigeon_mac"
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: ${{ matrix.name }}
          EXTRA_FILES: "README.md LICENSE"
          SRC_DIR: engine